<?php

namespace SiteBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
	public function dispLastFive()
	{
		$em = $this->getDoctrine()->getEntityManager();
		$query->select('*')
   			->from('Evenement')
   			->orderBy('id', 'DESC');

		return $query->setMaxResults(5)->getResult();
	}
}
